FROM python:3.10-slim-bookworm

ENV HADOOP_VERSION=3
ENV SPARK_VERSION=3.3.0

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    jupyterlab \
    pyspark==${SPARK_VERSION} \
    pandas \
    pyarrow

WORKDIR /opt/notebooks

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
